version: '3'


services:

  app:
    container_name: app
    build:
      context: .
    ports:
      - "5000:5000"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=appadmin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  postgres-exporter:
    image: docker.io/bitnami/postgres-exporter:0
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_URI=postgres:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=appadmin
      - DATA_SOURCE_PASS=password
      - PG_EXPORTER_AUTO_DISCOVER_DATABASES=true
    ports:
    - 9187:9187
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
    - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports: 
    - 3000:3000
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  loki:
    image: grafana/loki:master
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    # send Loki traces to Jaeger
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  jaeger:
    image: jaegertracing/all-in-one:1.30
    container_name: jaeger
    ports:
      - '6831:6831'
      - '16686:16686'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'