services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_IP=${BACKEND_IP}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"

  
  backend:
    container_name: backend
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
    - "5001:5001"


  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro



  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    ports: 
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.30
    container_name: jaeger
    ports:
      - "6831:6831"
      - "16686:16686"

  loki:
    container_name: loki
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml


  promtail:
    container_name: promtail
    image: grafana/promtail:1.4.1
    volumes:
      - /var/lib/docker/:/var/lib/docker/:ro
      - ./promtail/config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml