scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: grafana
    scrape_interval: 10s
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: postgres-exporter
    scrape_interval: 10s
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: jaeger
    scrape_interval: 10s
    static_configs:
      - targets: ["jaeger:14269"]
